# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20161010_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MicroServiceLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='dashboard.MicroService')),
            ],
        ),
        migrations.AlterField(
            model_name='bikestationdata',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
