# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_weatherstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='wid',
        ),
    ]
